//package solar.test;
//
//import static org.junit.Assert.*;
//import static org.mockito.Mockito.mock;
//import static org.mockito.Mockito.when;
//
//import java.util.ArrayList;
//import java.util.List;
//
//import javax.persistence.EntityManager;
//import javax.persistence.Query;
//
//import org.junit.Before;
//import org.junit.Test;
//import org.mockito.InjectMocks;
//import org.mockito.Mock;
//import org.mockito.Mockito;
//import org.mockito.MockitoAnnotations;
//import org.mockito.Spy;
//
//import com.PlayGroundAdv.Solar.Entity.AuthentificationEntity;
//import com.PlayGroundAdv.Solar.Entity.ElectricalUtilityEntity;
//import com.PlayGroundAdv.Solar.Entity.PathEntity;
//import com.PlayGroundAdv.Solar.Entity.PermitEntity;
//import com.PlayGroundAdv.Solar.Entity.PlansetCustomizeSheets;
//import com.PlayGroundAdv.Solar.Entity.UserLicSectionsEntity;
//import com.PlayGroundAdv.Solar.model.AuthentificationEntityResult;
//import com.PlayGroundAdv.Solar.model.EditUserInformations;
//import com.PlayGroundAdv.Solar.model.PermitHomeSiteEntityResult;
//import com.PlayGroundAdv.Solar.Services.CheckValueTypesService;
//import com.PlayGroundAdv.Solar.Services.PermitServiceEdit;
//import com.PlayGroundAdv.Solar.Services.PlansetServiceN001;
//
//public class TestPlansetServiceN001 {
//	@Mock
//    private EntityManager em;
//
//	@Spy
//	private CheckValueTypesService checkValueTypesService;
//
//	@Spy
//	private PermitServiceEdit permitServiceEdit;
//
//    @InjectMocks
//    PlansetServiceN001 plansetServiceN001 = new PlansetServiceN001();
//
//    @Before
//    public void setupMock() {
//    	plansetServiceN001 = new PlansetServiceN001();
//       MockitoAnnotations.initMocks(this);
//    }
//    @Test
//	public void testbuildingPDFN001() {
//    	List<List<Object>> scenario = new ArrayList<List<Object>>();
//    	List<PlansetCustomizeSheets> PlansetCustomizeSheets =null;
//    	PermitEntity permit =null;
//    	scenario.add(new ArrayList<Object>());
//		scenario.get(0).add(null);
//		scenario.get(0).add(null);
//		scenario.get(0).add(null);
//		scenario.get(0).add(null);
//		scenario.get(0).add(null);
//		scenario.get(0).add(null);
//		scenario.get(0).add(null);
//		scenario.get(0).add(null);
//		scenario.get(0).add(null);
//		scenario.get(0).add(null);
//		scenario.get(0).add(PlansetCustomizeSheets);
//		scenario.get(0).add(permit);
//		scenario.get(0).add(null);
//		scenario.get(0).add(null);
//
//		scenario.add(new ArrayList<Object>());
//		PermitHomeSiteEntityResult permitHomeSite1 = new PermitHomeSiteEntityResult();
//		scenario.get(1).add(permitHomeSite1);
//		scenario.get(1).add(null);
//		scenario.get(1).add(null);
//		scenario.get(1).add(null);
//		scenario.get(1).add("14kk44");
//		scenario.get(1).add(null);
//		scenario.get(1).add(null);
//		scenario.get(1).add(null);
//		scenario.get(1).add(null);
//		AuthentificationEntity userConnectedEntity1= new AuthentificationEntity();
//		scenario.get(1).add(userConnectedEntity1);
//		scenario.get(1).add(PlansetCustomizeSheets);
//		scenario.get(1).add(permit);
//		scenario.get(1).add(null);
//		scenario.get(1).add(null);
//
//		scenario.add(new ArrayList<Object>());
//		PermitHomeSiteEntityResult permitHomeSite2 = new PermitHomeSiteEntityResult();
//		scenario.get(2).add(permitHomeSite2);
//		scenario.get(2).add(null);
//		scenario.get(2).add(null);
//		scenario.get(2).add(null);
//		scenario.get(2).add("14545");
//		scenario.get(2).add(null);
//		scenario.get(2).add(null);
//		scenario.get(2).add(null);
//		scenario.get(2).add(null);
//		AuthentificationEntity userConnectedEntity2= new AuthentificationEntity();
//		scenario.get(2).add(userConnectedEntity2);
//		scenario.get(2).add(PlansetCustomizeSheets);
//		scenario.get(2).add(permit);
//		scenario.get(2).add(null);
//		scenario.get(2).add(null);
//
//		scenario.add(new ArrayList<Object>());
//		scenario.get(3).add(null);
//		scenario.get(3).add(null);
//		scenario.get(3).add(null);
//		scenario.get(3).add(null);
//		scenario.get(3).add("14545");
//		scenario.get(3).add(null);
//		scenario.get(3).add(null);
//		scenario.get(3).add(null);
//		scenario.get(3).add(null);
//		AuthentificationEntity userConnectedEntity3= new AuthentificationEntity();
//		scenario.get(3).add(userConnectedEntity3);
//		scenario.get(3).add(PlansetCustomizeSheets);
//		PermitEntity permit3 = new PermitEntity();
//		permit3.setPlansetVersion(2);
//		permit3.setPlansetState("CA");
//		scenario.get(3).add(permit3);
//		scenario.get(3).add(null);
//		scenario.get(3).add(null);
//
//		scenario.add(new ArrayList<Object>());
//		PermitHomeSiteEntityResult permitHomeSite4 = new PermitHomeSiteEntityResult();
//		permitHomeSite4.setState("NY");
//		scenario.get(4).add(permitHomeSite4);
//		AuthentificationEntityResult userLogedInfo4 = new AuthentificationEntityResult();
//		scenario.get(4).add(userLogedInfo4);
//		scenario.get(4).add(null);
//		EditUserInformations editUserInformations4 = new EditUserInformations();
//		scenario.get(4).add(editUserInformations4);
//		scenario.get(4).add("14545");
//		scenario.get(4).add(null);
//		scenario.get(4).add(null);
//		scenario.get(4).add(null);
//		scenario.get(4).add(null);
//		AuthentificationEntity userConnectedEntity4= new AuthentificationEntity();
//		scenario.get(4).add(userConnectedEntity4);
//		List<PlansetCustomizeSheets> customizeSheets4 = new ArrayList<PlansetCustomizeSheets>();
//		PlansetCustomizeSheets customizeSheets40 =new PlansetCustomizeSheets();
//		customizeSheets4.add(customizeSheets40);
//		PlansetCustomizeSheets customizeSheets41 =new PlansetCustomizeSheets();
//		customizeSheets41.setIndividualAHJ("City of AHJ");
//		customizeSheets41.setUsers("FirstName LastName");
//		customizeSheets41.setUtilityCompany("utilityCompany");
//		customizeSheets4.add(customizeSheets41);
//		PlansetCustomizeSheets customizeSheets42 =new PlansetCustomizeSheets();
//		customizeSheets42.setIndividualAHJ("City of AHJ");
//		customizeSheets42.setUtilityCompany("utilityCompany");
//		customizeSheets4.add(customizeSheets42);
//		PlansetCustomizeSheets customizeSheets43 =new PlansetCustomizeSheets();
//		customizeSheets43.setUsers("FirstName LastName");
//		customizeSheets43.setUtilityCompany("utilityCompany");
//		customizeSheets4.add(customizeSheets43);
//		PlansetCustomizeSheets customizeSheets44 =new PlansetCustomizeSheets();
//		customizeSheets44.setIndividualAHJ("City of AHJ");
//		customizeSheets44.setUsers("FirstName LastName");
//		customizeSheets4.add(customizeSheets44);
//		PlansetCustomizeSheets customizeSheets45 =new PlansetCustomizeSheets();
//		customizeSheets45.setUtilityCompany("utilityCompany");
//		customizeSheets4.add(customizeSheets45);
//		PlansetCustomizeSheets customizeSheets46 =new PlansetCustomizeSheets();
//		customizeSheets46.setUsers("FirstName LastName");
//		customizeSheets4.add(customizeSheets46);
//		PlansetCustomizeSheets customizeSheets47 =new PlansetCustomizeSheets();
//		customizeSheets47.setIndividualAHJ("City of AHJ");
//		customizeSheets4.add(customizeSheets47);
//		scenario.get(4).add(customizeSheets4);
//		PermitEntity permit4 = new PermitEntity();
//		permit4.setPlansetVersion(4);
//		permit4.setPlansetState("CA");
//		scenario.get(4).add(permit4);
//		scenario.get(4).add(null);
//		scenario.get(4).add(null);
//
//		scenario.add(new ArrayList<Object>());
//		PermitHomeSiteEntityResult permitHomeSite5 = new PermitHomeSiteEntityResult();
//		permitHomeSite5.setState("NY");
//		scenario.get(5).add(permitHomeSite5);
//		AuthentificationEntityResult userLogedInfo5 = new AuthentificationEntityResult();
//		scenario.get(5).add(userLogedInfo5);
//		scenario.get(5).add(null);
//		EditUserInformations editUserInformations5 = new EditUserInformations();
//		editUserInformations5.setContractorLicenceState("NY");
//		scenario.get(5).add(editUserInformations5);
//		scenario.get(5).add("15555");
//		scenario.get(5).add(null);
//		PermitEntity permitEntity5 = new PermitEntity();
//		scenario.get(5).add(permitEntity5);
//		scenario.get(5).add(null);
//		ElectricalUtilityEntity electricalCompany5= new ElectricalUtilityEntity();
//		scenario.get(5).add(electricalCompany5);
//		AuthentificationEntity userConnectedEntity5= new AuthentificationEntity();
//		scenario.get(5).add(userConnectedEntity5);
//		List<PlansetCustomizeSheets> customizeSheets5 = new ArrayList<PlansetCustomizeSheets>();
//		PlansetCustomizeSheets customizeSheets50 =new PlansetCustomizeSheets();
//		customizeSheets5.add(customizeSheets50);
//		PlansetCustomizeSheets customizeSheets51 =new PlansetCustomizeSheets();
//		customizeSheets51.setIndividualAHJ("City of AHJ");
//		customizeSheets51.setUsers("FirstName LastName");
//		customizeSheets51.setUtilityCompany("utilityCompany");
//		customizeSheets5.add(customizeSheets51);
//		PlansetCustomizeSheets customizeSheets52 =new PlansetCustomizeSheets();
//		customizeSheets52.setIndividualAHJ("City of AHJ");
//		customizeSheets52.setUtilityCompany("utilityCompany");
//		customizeSheets5.add(customizeSheets52);
//		PlansetCustomizeSheets customizeSheets53 =new PlansetCustomizeSheets();
//		customizeSheets53.setUsers("FirstName LastName");
//		customizeSheets53.setUtilityCompany("utilityCompany");
//		customizeSheets5.add(customizeSheets53);
//		PlansetCustomizeSheets customizeSheets54 =new PlansetCustomizeSheets();
//		customizeSheets54.setIndividualAHJ("City of AHJ");
//		customizeSheets54.setUsers("FirstName LastName");
//		customizeSheets5.add(customizeSheets54);
//		PlansetCustomizeSheets customizeSheets55 =new PlansetCustomizeSheets();
//		customizeSheets55.setUtilityCompany("utilityCompany");
//		customizeSheets5.add(customizeSheets55);
//		PlansetCustomizeSheets customizeSheets56 =new PlansetCustomizeSheets();
//		customizeSheets56.setUsers("FirstName LastName");
//		customizeSheets5.add(customizeSheets56);
//		PlansetCustomizeSheets customizeSheets57 =new PlansetCustomizeSheets();
//		customizeSheets57.setIndividualAHJ("City of AHJ");
//		customizeSheets5.add(customizeSheets57);
//		scenario.get(5).add(customizeSheets5);
//		PermitEntity permit5 = new PermitEntity();
//		permit5.setPlansetVersion(5);
//		permit5.setPlansetState("CA");
//		scenario.get(5).add(permit5);
//		List<UserLicSectionsEntity> userLicSectionList5 = new ArrayList<UserLicSectionsEntity>();
//		scenario.get(5).add(userLicSectionList5);
//		scenario.get(5).add(null);
//
//		scenario.add(new ArrayList<Object>());
//		PermitHomeSiteEntityResult permitHomeSite6 = new PermitHomeSiteEntityResult();
//		permitHomeSite6.setState("NY");
//		scenario.get(6).add(permitHomeSite6);
//		AuthentificationEntityResult userLogedInfo6 = new AuthentificationEntityResult();
//		scenario.get(6).add(userLogedInfo6);
//		scenario.get(6).add(null);
//		EditUserInformations editUserInformations6 = new EditUserInformations();
//		scenario.get(6).add(editUserInformations6);
//		scenario.get(6).add("16666");
//		scenario.get(6).add(null);
//		PermitEntity permitEntity6 = new PermitEntity();
//		scenario.get(6).add(permitEntity6);
//		scenario.get(6).add(null);
//		ElectricalUtilityEntity electricalCompany6= new ElectricalUtilityEntity();
//		electricalCompany6.setUtilityCompanyName("Other");
//		scenario.get(6).add(electricalCompany6);
//		AuthentificationEntity userConnectedEntity6= new AuthentificationEntity();
//		scenario.get(6).add(userConnectedEntity6);
//		List<PlansetCustomizeSheets> customizeSheets6 = new ArrayList<PlansetCustomizeSheets>();
//		PlansetCustomizeSheets customizeSheets60 =new PlansetCustomizeSheets();
//		customizeSheets6.add(customizeSheets60);
//		PlansetCustomizeSheets customizeSheets61 =new PlansetCustomizeSheets();
//		customizeSheets61.setIndividualAHJ("City of AHJ");
//		customizeSheets61.setUsers("FirstName LastName");
//		customizeSheets61.setUtilityCompany("utilityCompany");
//		customizeSheets6.add(customizeSheets61);
//		PlansetCustomizeSheets customizeSheets62 =new PlansetCustomizeSheets();
//		customizeSheets62.setIndividualAHJ("City of AHJ");
//		customizeSheets62.setUtilityCompany("utilityCompany");
//		customizeSheets6.add(customizeSheets62);
//		PlansetCustomizeSheets customizeSheets63 =new PlansetCustomizeSheets();
//		customizeSheets63.setUsers("FirstName LastName");
//		customizeSheets63.setUtilityCompany("utilityCompany");
//		customizeSheets6.add(customizeSheets63);
//		PlansetCustomizeSheets customizeSheets64 =new PlansetCustomizeSheets();
//		customizeSheets64.setIndividualAHJ("City of AHJ");
//		customizeSheets64.setUsers("FirstName LastName");
//		customizeSheets6.add(customizeSheets64);
//		PlansetCustomizeSheets customizeSheets65 =new PlansetCustomizeSheets();
//		customizeSheets65.setUtilityCompany("utilityCompany");
//		customizeSheets6.add(customizeSheets65);
//		PlansetCustomizeSheets customizeSheets66 =new PlansetCustomizeSheets();
//		customizeSheets66.setUsers("FirstName LastName");
//		customizeSheets6.add(customizeSheets66);
//		PlansetCustomizeSheets customizeSheets67 =new PlansetCustomizeSheets();
//		customizeSheets67.setIndividualAHJ("City of AHJ");
//		customizeSheets6.add(customizeSheets67);
//		scenario.get(6).add(customizeSheets6);
//		PermitEntity permit6 = new PermitEntity();
//		permit6.setPlansetVersion(6);
//		permit6.setPlansetState("CA");
//		scenario.get(6).add(permit6);
//		List<UserLicSectionsEntity> userLicSectionList6 = new ArrayList<UserLicSectionsEntity>();
//		UserLicSectionsEntity userLicSection6 = new UserLicSectionsEntity();
//		userLicSectionList6.add(userLicSection6);
//		scenario.get(6).add(userLicSectionList6);
//		scenario.get(6).add(null);
//
//
//		scenario.add(new ArrayList<Object>());
//		PermitHomeSiteEntityResult permitHomeSite7 = new PermitHomeSiteEntityResult();
//		permitHomeSite7.setState("NY");
//		scenario.get(7).add(permitHomeSite7);
//		AuthentificationEntityResult userLogedInfo7 = new AuthentificationEntityResult();
//		scenario.get(7).add(userLogedInfo7);
//		scenario.get(7).add(null);
//		EditUserInformations editUserInformations7 = new EditUserInformations();
//		scenario.get(7).add(editUserInformations7);
//		scenario.get(7).add("17777");
//		scenario.get(7).add(null);
//		PermitEntity permitEntity7 = new PermitEntity();
//		scenario.get(7).add(permitEntity7);
//		scenario.get(7).add(null);
//		ElectricalUtilityEntity electricalCompany7= new ElectricalUtilityEntity();
//		electricalCompany7.setUtilityCompanyName("utilityCompany");
//		scenario.get(7).add(electricalCompany7);
//		AuthentificationEntity userConnectedEntity7= new AuthentificationEntity();
//		scenario.get(7).add(userConnectedEntity7);
//		List<PlansetCustomizeSheets> customizeSheets7 = new ArrayList<PlansetCustomizeSheets>();
//		PlansetCustomizeSheets customizeSheets70 =new PlansetCustomizeSheets();
//		customizeSheets70.setId(1);
//		customizeSheets7.add(customizeSheets70);
//		PlansetCustomizeSheets customizeSheets71 =new PlansetCustomizeSheets();
//		customizeSheets71.setId(1);
//		customizeSheets71.setIndividualAHJ("City of AHJ");
//		customizeSheets71.setUsers("FirstName LastName");
//		customizeSheets71.setUtilityCompany("utilityCompany");
//		customizeSheets7.add(customizeSheets71);
//		PlansetCustomizeSheets customizeSheets72 =new PlansetCustomizeSheets();
//		customizeSheets72.setId(1);
//		customizeSheets72.setIndividualAHJ("City of AHJ");
//		customizeSheets72.setUtilityCompany("utilityCompany");
//		customizeSheets7.add(customizeSheets72);
//		PlansetCustomizeSheets customizeSheets73 =new PlansetCustomizeSheets();
//		customizeSheets73.setId(1);
//		customizeSheets73.setUsers("FirstName LastName");
//		customizeSheets73.setUtilityCompany("utilityCompany");
//		customizeSheets7.add(customizeSheets73);
//		PlansetCustomizeSheets customizeSheets74 =new PlansetCustomizeSheets();
//		customizeSheets74.setId(1);
//		customizeSheets74.setIndividualAHJ("City of AHJ");
//		customizeSheets74.setUsers("FirstName LastName");
//		customizeSheets7.add(customizeSheets74);
//		PlansetCustomizeSheets customizeSheets75 =new PlansetCustomizeSheets();
//		customizeSheets75.setId(1);
//		customizeSheets75.setUtilityCompany("utilityCompany");
//		customizeSheets7.add(customizeSheets75);
//		PlansetCustomizeSheets customizeSheets76 =new PlansetCustomizeSheets();
//		customizeSheets76.setId(1);
//		customizeSheets76.setUsers("FirstName LastName");
//		customizeSheets7.add(customizeSheets76);
//		PlansetCustomizeSheets customizeSheets77 =new PlansetCustomizeSheets();
//		customizeSheets77.setId(1);
//		customizeSheets77.setIndividualAHJ("City of AHJ");
//		customizeSheets7.add(customizeSheets77);
//		scenario.get(7).add(customizeSheets7);
//		PermitEntity permit7 = new PermitEntity();
//		permit7.setPlansetVersion(7);
//		permit7.setPlansetState("CA");
//		scenario.get(7).add(permit7);
//		List<UserLicSectionsEntity> userLicSectionList7 = new ArrayList<UserLicSectionsEntity>();
//		UserLicSectionsEntity userLicSection7 = new UserLicSectionsEntity();
//		userLicSectionList7.add(userLicSection7);
//		scenario.get(7).add(userLicSectionList7);
//		scenario.get(7).add(userLicSection7);
//
//
//		scenario.add(new ArrayList<Object>());
//		PermitHomeSiteEntityResult permitHomeSite8 = new PermitHomeSiteEntityResult();
//		permitHomeSite8.setState("NY");
//		permitHomeSite8.setProjectJurisdiction("city");
//		scenario.get(8).add(permitHomeSite8);
//		AuthentificationEntityResult userLogedInfo8 = new AuthentificationEntityResult();
//		scenario.get(8).add(userLogedInfo8);
//		scenario.get(8).add(null);
//		EditUserInformations editUserInformations8 = new EditUserInformations();
//		scenario.get(8).add(editUserInformations8);
//		scenario.get(8).add("18888");
//		scenario.get(8).add(null);
//		PermitEntity permitEntity8 = new PermitEntity();
//		permitEntity8.setReleasev2("releasev2");
//		scenario.get(8).add(permitEntity8);
//		scenario.get(8).add(null);
//		ElectricalUtilityEntity electricalCompany8= new ElectricalUtilityEntity();
//		electricalCompany8.setUtilityCompanyName("utilityCompany");
//		scenario.get(8).add(electricalCompany8);
//		AuthentificationEntity userConnectedEntity8= new AuthentificationEntity();
//		scenario.get(8).add(userConnectedEntity8);
//		List<PlansetCustomizeSheets> customizeSheets8 = new ArrayList<PlansetCustomizeSheets>();
//		PlansetCustomizeSheets customizeSheets80 =new PlansetCustomizeSheets();
//		customizeSheets80.setId(1);
//		customizeSheets8.add(customizeSheets80);
//		PlansetCustomizeSheets customizeSheets81 =new PlansetCustomizeSheets();
//		customizeSheets81.setId(1);
//		customizeSheets81.setIndividualAHJ("City of ");
//		customizeSheets81.setUsers("FirstName LastName");
//		customizeSheets81.setUtilityCompany("utilityCompany");
//		customizeSheets8.add(customizeSheets81);
//		PlansetCustomizeSheets customizeSheets82 =new PlansetCustomizeSheets();
//		customizeSheets82.setId(1);
//		customizeSheets82.setIndividualAHJ("City of AHJ");
//		customizeSheets82.setUtilityCompany("utilityCompany");
//		customizeSheets8.add(customizeSheets82);
//		PlansetCustomizeSheets customizeSheets83 =new PlansetCustomizeSheets();
//		customizeSheets83.setId(1);
//		customizeSheets83.setUsers("FirstName LastName");
//		customizeSheets83.setUtilityCompany("utilityCompany");
//		customizeSheets8.add(customizeSheets83);
//		PlansetCustomizeSheets customizeSheets84 =new PlansetCustomizeSheets();
//		customizeSheets84.setId(1);
//		customizeSheets84.setIndividualAHJ("City of AHJ");
//		customizeSheets84.setUsers("FirstName LastName");
//		customizeSheets8.add(customizeSheets84);
//		PlansetCustomizeSheets customizeSheets85 =new PlansetCustomizeSheets();
//		customizeSheets85.setId(1);
//		customizeSheets85.setUtilityCompany("utilityCompany");
//		customizeSheets8.add(customizeSheets85);
//		PlansetCustomizeSheets customizeSheets86 =new PlansetCustomizeSheets();
//		customizeSheets86.setId(1);
//		customizeSheets86.setUsers("FirstName LastName");
//		customizeSheets8.add(customizeSheets86);
//		PlansetCustomizeSheets customizeSheets87 =new PlansetCustomizeSheets();
//		customizeSheets87.setId(1);
//		customizeSheets87.setIndividualAHJ("City of AHJ");
//		customizeSheets8.add(customizeSheets87);
//		scenario.get(8).add(customizeSheets8);
//		PermitEntity permit8 = new PermitEntity();
//		permit8.setPlansetVersion(8);
//		permit8.setPlansetState("CA");
//		scenario.get(8).add(permit8);
//		List<UserLicSectionsEntity> userLicSectionList8 = new ArrayList<UserLicSectionsEntity>();
//		UserLicSectionsEntity userLicSection8 = new UserLicSectionsEntity();
//		userLicSection8.setContractorLicenceState("CA");
//		userLicSectionList8.add(userLicSection8);
//		scenario.get(8).add(userLicSectionList8);
//		scenario.get(8).add(userLicSection8);
//
//
//		scenario.add(new ArrayList<Object>());
//		PermitHomeSiteEntityResult permitHomeSite9 = new PermitHomeSiteEntityResult();
//		permitHomeSite9.setState("NY");
//		permitHomeSite9.setProjectJurisdiction("city");
//		scenario.get(9).add(permitHomeSite9);
//		AuthentificationEntityResult userLogedInfo9 = new AuthentificationEntityResult();
//		scenario.get(9).add(userLogedInfo9);
//		scenario.get(9).add(null);
//		EditUserInformations editUserInformations9 = new EditUserInformations();
//		scenario.get(9).add(editUserInformations9);
//		scenario.get(9).add("19999");
//		scenario.get(9).add(null);
//		PermitEntity permitEntity9 = new PermitEntity();
//		AuthentificationEntity authentificationEntity9 = new AuthentificationEntity();
//		permitEntity9.setAuthentificationEntity(authentificationEntity9);
//		scenario.get(9).add(permitEntity9);
//		scenario.get(9).add(null);
//		ElectricalUtilityEntity electricalCompany9= new ElectricalUtilityEntity();
//		electricalCompany9.setUtilityCompanyName("utilityCompany");
//		scenario.get(9).add(electricalCompany9);
//		AuthentificationEntity userConnectedEntity9= new AuthentificationEntity();
//		scenario.get(9).add(userConnectedEntity9);
//		List<PlansetCustomizeSheets> customizeSheets9 = new ArrayList<PlansetCustomizeSheets>();
//		PlansetCustomizeSheets customizeSheets90 =new PlansetCustomizeSheets();
//		customizeSheets90.setId(1);
//		customizeSheets9.add(customizeSheets90);
//		PlansetCustomizeSheets customizeSheets91 =new PlansetCustomizeSheets();
//		customizeSheets91.setId(1);
//		customizeSheets91.setIndividualAHJ("City of ");
//		customizeSheets91.setUsers("FirstName LastName");
//		customizeSheets91.setUtilityCompany("utilityCompany");
//		customizeSheets9.add(customizeSheets91);
//		PlansetCustomizeSheets customizeSheets92 =new PlansetCustomizeSheets();
//		customizeSheets92.setId(1);
//		customizeSheets92.setIndividualAHJ("City of AHJ");
//		customizeSheets92.setUtilityCompany("utilityCompany");
//		customizeSheets9.add(customizeSheets92);
//		PlansetCustomizeSheets customizeSheets93 =new PlansetCustomizeSheets();
//		customizeSheets93.setId(1);
//		customizeSheets93.setUsers("FirstName LastName");
//		customizeSheets93.setUtilityCompany("utilityCompany");
//		customizeSheets9.add(customizeSheets93);
//		PlansetCustomizeSheets customizeSheets94 =new PlansetCustomizeSheets();
//		customizeSheets94.setId(1);
//		customizeSheets94.setIndividualAHJ("City of AHJ");
//		customizeSheets94.setUsers("FirstName LastName");
//		customizeSheets9.add(customizeSheets94);
//		PlansetCustomizeSheets customizeSheets95 =new PlansetCustomizeSheets();
//		customizeSheets95.setId(1);
//		customizeSheets95.setUtilityCompany("utilityCompany");
//		customizeSheets9.add(customizeSheets95);
//		PlansetCustomizeSheets customizeSheets96 =new PlansetCustomizeSheets();
//		customizeSheets96.setId(1);
//		customizeSheets96.setUsers("FirstName LastName");
//		customizeSheets9.add(customizeSheets96);
//		PlansetCustomizeSheets customizeSheets97 =new PlansetCustomizeSheets();
//		customizeSheets97.setId(1);
//		customizeSheets97.setIndividualAHJ("City of AHJ");
//		customizeSheets9.add(customizeSheets97);
//		scenario.get(9).add(customizeSheets9);
//		PermitEntity permit9 = new PermitEntity();
//		permit9.setPlansetVersion(9);
//		permit9.setPlansetState("CA");
//		scenario.get(9).add(permit9);
//		scenario.get(9).add(null);
//		scenario.get(9).add(null);
//
//
//		scenario.add(new ArrayList<Object>());
//		PermitHomeSiteEntityResult permitHomeSite10 = new PermitHomeSiteEntityResult();
//		permitHomeSite10.setState("NY");
//		permitHomeSite10.setProjectJurisdiction("city");
//		scenario.get(10).add(permitHomeSite10);
//		AuthentificationEntityResult userLogedInfo10 = new AuthentificationEntityResult();
//		scenario.get(10).add(userLogedInfo10);
//		scenario.get(10).add(null);
//		scenario.get(10).add(null);
//		scenario.get(10).add("110101010");
//		scenario.get(10).add(null);
//		PermitEntity permitEntity10 = new PermitEntity();
//		AuthentificationEntity authentificationEntity10 = new AuthentificationEntity();
//		authentificationEntity10.setFirstName("FirstName");
//		authentificationEntity10.setLastName("LastName");
//		permitEntity10.setAuthentificationEntity(authentificationEntity10);
//		scenario.get(10).add(permitEntity10);
//		scenario.get(10).add(null);
//		ElectricalUtilityEntity electricalCompany10= new ElectricalUtilityEntity();
//		electricalCompany10.setUtilityCompanyName("utilityCompany");
//		scenario.get(10).add(electricalCompany10);
//		AuthentificationEntity userConnectedEntity10= new AuthentificationEntity();
//		scenario.get(10).add(userConnectedEntity10);
//		List<PlansetCustomizeSheets> customizeSheets10 = new ArrayList<PlansetCustomizeSheets>();
//		PlansetCustomizeSheets customizeSheets100 =new PlansetCustomizeSheets();
//		customizeSheets100.setId(1);
//		customizeSheets10.add(customizeSheets100);
//		PlansetCustomizeSheets customizeSheets101 =new PlansetCustomizeSheets();
//		customizeSheets101.setId(1);
//		customizeSheets101.setIndividualAHJ("City of ");
//		customizeSheets101.setUsers("FirstName LastName");
//		customizeSheets101.setUtilityCompany("utilityCompany");
//		customizeSheets10.add(customizeSheets101);
//		PlansetCustomizeSheets customizeSheets102 =new PlansetCustomizeSheets();
//		customizeSheets102.setId(1);
//		customizeSheets102.setIndividualAHJ("City of AHJ");
//		customizeSheets102.setUtilityCompany("utilityCompany");
//		customizeSheets10.add(customizeSheets102);
//		PlansetCustomizeSheets customizeSheets103 =new PlansetCustomizeSheets();
//		customizeSheets103.setId(1);
//		customizeSheets103.setUsers("FirstName LastName");
//		customizeSheets103.setUtilityCompany("utilityCompany");
//		customizeSheets10.add(customizeSheets103);
//		PlansetCustomizeSheets customizeSheets104 =new PlansetCustomizeSheets();
//		customizeSheets104.setId(1);
//		customizeSheets104.setIndividualAHJ("City of AHJ");
//		customizeSheets104.setUsers("FirstName LastName");
//		customizeSheets10.add(customizeSheets104);
//		PlansetCustomizeSheets customizeSheets105 =new PlansetCustomizeSheets();
//		customizeSheets105.setId(1);
//		customizeSheets105.setUtilityCompany("utilityCompany");
//		customizeSheets10.add(customizeSheets105);
//		PlansetCustomizeSheets customizeSheets106 =new PlansetCustomizeSheets();
//		customizeSheets106.setId(1);
//		customizeSheets106.setUsers("FirstName LastName");
//		customizeSheets10.add(customizeSheets106);
//		PlansetCustomizeSheets customizeSheets107 =new PlansetCustomizeSheets();
//		customizeSheets107.setId(1);
//		customizeSheets107.setIndividualAHJ("City of AHJ");
//		customizeSheets10.add(customizeSheets107);
//		scenario.get(10).add(customizeSheets10);
//		PermitEntity permit10 = new PermitEntity();
//		permit10.setPlansetVersion(10);
//		permit10.setPlansetState("CA");
//		scenario.get(10).add(permit10);
//		scenario.get(10).add(null);
//		scenario.get(10).add(null);
//
//
//		Query qCustomizeSheets = mock(Query.class);
//		when(em.createQuery("SELECT u from PlansetCustomizeSheets u where (u.pdfName =:p1 OR u.pdfName =:p3) AND u.isDeleted=:p2")).thenReturn(qCustomizeSheets);
//		when(qCustomizeSheets.setParameter(Mockito.anyString(),  Mockito.any())).thenReturn(qCustomizeSheets);
//
//	    Query queryVersion = mock(Query.class);
//		when(em.createQuery("SELECT u " + " from PermitEntity u " + " where u.id = :p1 ")).thenReturn(queryVersion);
//		when(queryVersion.setParameter(Mockito.anyString(),  Mockito.any())).thenReturn(queryVersion);
//
//		Query q = mock(Query.class);
//		when(em.createQuery("SELECT u.companyLogoName from UserSettingEntity u where u.userId.id =:p1 and u.logoConfirmed=:p2")).thenReturn(q);
//		when(q.setParameter(Mockito.anyString(),  Mockito.any())).thenReturn(q);
//		when(q.getSingleResult()).thenReturn(null);
//
//		Query q1 = mock(Query.class);
//		when(em.createQuery("SELECT u.signature from UserSettingEntity u where u.userId.id =:p1 and u.signatureConfirmed=:p2")).thenReturn(q1);
//		when(q1.setParameter(Mockito.anyString(),  Mockito.any())).thenReturn(q);
//		when(q1.getSingleResult()).thenReturn(null);
//
//		Query query = mock(Query.class);
//		when(em.createQuery("SELECT u from UserLicSectionsEntity u WHERE u.authentificationEntity.id = :p1 AND u.contractorLicenceState= :p2")).thenReturn(query);
//		when(query.setParameter(Mockito.anyString(),  Mockito.any())).thenReturn(query);
//
//
//	}
//
//}
